const ERROR_WRONG_DATA_STATUS_CODE = 400;
const ERROR_UNAUTHORIZED_STATUS_CODE = 401;
const ERROR_FORBIDDEN_STATUS_CODE = 403;
const ERROR_NOT_FOUND_STATUS_CODE = 404;
const ERROR_CONFLICT_STATUS_CODE = 409;
const ERROR_INTERNAL_STATUS_CODE = 500;

module.exports = {
  ERROR_WRONG_DATA_STATUS_CODE,
  ERROR_UNAUTHORIZED_STATUS_CODE,
  ERROR_FORBIDDEN_STATUS_CODE,
  ERROR_NOT_FOUND_STATUS_CODE,
  ERROR_CONFLICT_STATUS_CODE,
  ERROR_INTERNAL_STATUS_CODE,
};
