const ERROR_WRONG_DATA_STATUS_CODE = 400;
const ERROR_UNAUTHORIZED_STATUS_CODE = 401;
const ERROR_FORBIDDEN_STATUS_CODE = 403;
const ERROR_NOT_FOUND_STATUS_CODE = 404;
const ERROR_CONFLICT_STATUS_CODE = 409;
const ERROR_INTERNAL_STATUS_CODE = 500;

const ERROR_UNAUTHORIZED_STATUS_MESSAGE = 'Необходима авторизация';
const ERROR_JWT_UNAUTHORIZED_STATUS_MESSAGE = 'JWT авторизация не прошла';

const ERROR_NOT_FOUND_STATUS_MESSAGE = 'Запрашиваемый ресурс не найден';
const ERROR_MOVIE_NOT_FOUND_STATUS_MESSAGE = 'Фильм по данным id не найден';
const ERROR_CONFLICT_STATUS_MESSAGE = 'Пользователь с таким email уже существует';
const ERROR_INTERNAL_STATUS_MESSAGE = 'На сервере произошла ошибка';

const ERROR_WRONG_URL_MESSAGE = 'Неверно указана ссылка';
const ERROR_WRONG_EMAIL_MESSAGE = 'Неправильный формат почты';
const ERROR_WRONG_EMAIL_OR_PASSWORD_MESSAGE = 'Неправильная почта или пароль';
const ERROR_USER_NOT_EXIST_MESSAGE = 'Такого пользователя не существует';
const ERROR_REQUEST_MESSAGE = 'Ошибка при запросе';

const ERROR_WRONG_USER_DATA_CREATE_STATUS_MESSAGE = 'Переданы некорректные данные при создании пользователя';
const ERROR_WRONG_USER_DATA_UPDATE_STATUS_MESSAGE = 'Переданы некорректные данные при обновлении профиля';

const ERROR_WRONG_MOVIES_DATA_CREATE_STATUS_MESSAGE = 'Переданы некорректные данные при создании карточки';
const ERROR_ACCESS_DENIED_MOVIE_REMOVE_MESSAGE = 'Чужой фильм нельзя удалить';
const ERROR_MOVIE_REMOVE_SUCCESS_MESSAGE = 'Фильм успешно удален';

module.exports = {
  ERROR_WRONG_DATA_STATUS_CODE,
  ERROR_UNAUTHORIZED_STATUS_CODE,
  ERROR_FORBIDDEN_STATUS_CODE,
  ERROR_NOT_FOUND_STATUS_CODE,
  ERROR_CONFLICT_STATUS_CODE,
  ERROR_INTERNAL_STATUS_CODE,
  ERROR_INTERNAL_STATUS_MESSAGE,
  ERROR_UNAUTHORIZED_STATUS_MESSAGE,
  ERROR_JWT_UNAUTHORIZED_STATUS_MESSAGE,
  ERROR_WRONG_URL_MESSAGE,
  ERROR_WRONG_EMAIL_MESSAGE,
  ERROR_WRONG_EMAIL_OR_PASSWORD_MESSAGE,
  ERROR_USER_NOT_EXIST_MESSAGE,
  ERROR_REQUEST_MESSAGE,
  ERROR_CONFLICT_STATUS_MESSAGE,
  ERROR_WRONG_USER_DATA_CREATE_STATUS_MESSAGE,
  ERROR_WRONG_USER_DATA_UPDATE_STATUS_MESSAGE,
  ERROR_NOT_FOUND_STATUS_MESSAGE,
  ERROR_WRONG_MOVIES_DATA_CREATE_STATUS_MESSAGE,
  ERROR_MOVIE_NOT_FOUND_STATUS_MESSAGE,
  ERROR_ACCESS_DENIED_MOVIE_REMOVE_MESSAGE,
  ERROR_MOVIE_REMOVE_SUCCESS_MESSAGE,
};
